require 'plugins'
require 'colorscheme'
require 'options'
require 'mappings'
require 'orgmode'
require 'treesitter'
require 'lsp'
require 'commands'
require 'statusline'
require 'bufferline'
require 'browser'
require 'complete'
require 'git'
require 'terminal'
-- require 'rpc'
